### ISSUE TITLE
history | awk '{print $2}' | sort | uniq -c | sort -rn | head as alias

### ISSUE THREAD

**Issue by jonpatterns** [arturoherrero/command-line-one-liners#9]
`history | awk '{print $2}' | sort | uniq -c | sort -rn | head`

Using the command to get most frequency used doesn't work as an alias, for example

`alias commhist="history | awk '{print $2}' | sort | uniq -c | sort -rn | head"`

Using `commhist` produces a list of commands prefixed by two numbers.

**Comment by arturoherrero** [comment]
Oh, I see the problem. You have to escape `$`.

This should works:
```
alias commhist="history | awk '{print \$2}' | sort | uniq -c | sort -rn | head"
```

**Comment by jonpatterns** [comment]
Brilliant, thanks this works : -)
